Remove openssh_server container on test exit
libssh2/libssh2 pull request #560
Opened 2021-02-28 06:56 UTC by stac47

Hello,
I propose to automatically remove the openssh_server containers on test exit. The reason is that we often don't have access to the CI/CD system to manually purge all the exited containers.

2021-05-28 14:04 UTC, mback2k commented
@stac47 can I kindly ask you to rebase this PR on current master and force-push? Thanks in advance!

2021-05-29 09:58 UTC, mback2k requested changes

2021-05-29 09:58 UTC, mback2k commented on tests/openssh_fixture.c
> +                           "docker run --rm -d -p %s:22 libssh2/openssh_server",
```
./tests/openssh_fixture.c:162:81: warning: Longer than 79 columns (LONGLINE)
                            "docker run --rm -d -p %s:22 libssh2/openssh_server",
```

2021-05-29 14:01 UTC, stac47 commented on tests/openssh_fixture.c
> +                           "docker run --rm -d -p %s:22 libssh2/openssh_server",
Fixed.

2021-05-30 09:41 UTC, mback2k approved these changes

2021-05-30 09:41 UTC, merged