Runtime engine detection
libssh2/libssh2 pull request #643
Opened 2021-11-22 15:22 UTC by BastienDurel

Proposition of an API to let the programmer know which crypto engine is used in libssh2

2021-11-22 17:53 UTC, willco007 requested changes
Looks good, just needs to return a none option with no backend.

2021-11-22 17:53 UTC, willco007 commented on src/version.c
> +    #error "Unhandled crypto engine"
You can build libssh2 with no crypto backend. It should return a `none` option instead of erroring here.

2021-11-24 15:32 UTC, BastienDurel commented
Hello, is this good now ?

2021-11-24 19:28 UTC, willco007 requested changes
The next version will be 1.11, changing the version strings here would be great. My only other thought is moving the `return libssh2_no_crypto` outside of the #if/elif block, but that's my personal preference more than anything. :)

2021-11-25 08:54 UTC, BastienDurel commented
I prefer keeping `return libssh2_no_crypto` inside the `#else` to prevent unreachable code. Some compiler may complain about it.

2021-12-07 10:42 UTC, BastienDurel commented
Hello,

any news ?

2022-01-05 18:43 UTC, willco007 requested changes
libssh2_crypto_engine.3 file needs to be added to the docs/CmakeLists.txt file as well as the Makefile.am.

2022-01-06 10:20 UTC, BastienDurel commented
Done

2022-01-06 18:06 UTC, merged